# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/minecraft/dev/Minecraft-Server-Tools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/minecraft/dev/Minecraft-Server-Tools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/minecraft/dev/Minecraft-Server-Tools/CMakeFiles /home/minecraft/dev/Minecraft-Server-Tools/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/minecraft/dev/Minecraft-Server-Tools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mcsrv-tools

# Build rule for target.
mcsrv-tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcsrv-tools
.PHONY : mcsrv-tools

# fast build rule for target.
mcsrv-tools/fast:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/build
.PHONY : mcsrv-tools/fast

Config.o: Config.cpp.o
.PHONY : Config.o

# target to build an object file
Config.cpp.o:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/Config.cpp.o
.PHONY : Config.cpp.o

Config.i: Config.cpp.i
.PHONY : Config.i

# target to preprocess a source file
Config.cpp.i:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/Config.cpp.i
.PHONY : Config.cpp.i

Config.s: Config.cpp.s
.PHONY : Config.s

# target to generate assembly for a file
Config.cpp.s:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/Config.cpp.s
.PHONY : Config.cpp.s

LogParser.o: LogParser.cpp.o
.PHONY : LogParser.o

# target to build an object file
LogParser.cpp.o:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/LogParser.cpp.o
.PHONY : LogParser.cpp.o

LogParser.i: LogParser.cpp.i
.PHONY : LogParser.i

# target to preprocess a source file
LogParser.cpp.i:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/LogParser.cpp.i
.PHONY : LogParser.cpp.i

LogParser.s: LogParser.cpp.s
.PHONY : LogParser.s

# target to generate assembly for a file
LogParser.cpp.s:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/LogParser.cpp.s
.PHONY : LogParser.cpp.s

Server.o: Server.cpp.o
.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i
.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s
.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/Server.cpp.s
.PHONY : Server.cpp.s

User.o: User.cpp.o
.PHONY : User.o

# target to build an object file
User.cpp.o:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/User.cpp.o
.PHONY : User.cpp.o

User.i: User.cpp.i
.PHONY : User.i

# target to preprocess a source file
User.cpp.i:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/User.cpp.i
.PHONY : User.cpp.i

User.s: User.cpp.s
.PHONY : User.s

# target to generate assembly for a file
User.cpp.s:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/User.cpp.s
.PHONY : User.cpp.s

UserManager.o: UserManager.cpp.o
.PHONY : UserManager.o

# target to build an object file
UserManager.cpp.o:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/UserManager.cpp.o
.PHONY : UserManager.cpp.o

UserManager.i: UserManager.cpp.i
.PHONY : UserManager.i

# target to preprocess a source file
UserManager.cpp.i:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/UserManager.cpp.i
.PHONY : UserManager.cpp.i

UserManager.s: UserManager.cpp.s
.PHONY : UserManager.s

# target to generate assembly for a file
UserManager.cpp.s:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/UserManager.cpp.s
.PHONY : UserManager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mcsrv-tools.dir/build.make CMakeFiles/mcsrv-tools.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mcsrv-tools"
	@echo "... rebuild_cache"
	@echo "... Config.o"
	@echo "... Config.i"
	@echo "... Config.s"
	@echo "... LogParser.o"
	@echo "... LogParser.i"
	@echo "... LogParser.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... User.o"
	@echo "... User.i"
	@echo "... User.s"
	@echo "... UserManager.o"
	@echo "... UserManager.i"
	@echo "... UserManager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

